server:
  port: 9999

spring:
  application:
    name: kits
  fileLocation: D:/ftpdata
  userName: admin
  password: 123456
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb