server:
  port: 9000

spring:
  application:
    name: kits
  fileLocation: /home/kits/file
  userName: admin
  password: 123456
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb